version: '1.0'
custom_plugin_paths: []
exclude_files: '.*\.md$|.*\.txt$'
exclude_lines: ''
plugins:
  Base64HighEntropyString:
    limit: 4.5
  HexHighEntropyString:
    limit: 3.0
  KeywordDetector:
    keyword_exclude: ''
  BasicAuthDetector: []
  JwtTokenDetector: []
  PrivateKeyDetector: []
  CustomTextPlugin:
    patterns:
      - name: 'Slack Token'
        pattern: 'xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-zA-Z0-9]{32}'
      - name: 'AWS Access Key'
        pattern: 'AKIA[0-9A-Z]{16}'
      - name: 'API Key'
        pattern: '(?:\\s|=|:|\")([0-9a-zA-Z]{32,45})'
      - name: 'HTTP/HTTPS APIs'
        pattern: 'https?://[a-zA-Z0-9.-]+(:[0-9]{1,5})?(/[a-zA-Z0-9.-]*)?(\?[a-zA-Z0-9.-]*)?'
      - name: 'Slack Webhook'
        pattern: 'https://hooks\.slack\.com/services/T[a-zA-Z0-9]{8}/B[a-zA-Z0-9]{8}/[a-zA-Z0-9]{24}'
